<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="Internet and Computing Fundamentals">
    <node ID="node_1" TEXT="Computer Software">
      <node ID="node_6" TEXT="System Software">
        <node ID="node_21" TEXT="Operating System">
          <node ID="node_51" TEXT="Windows">
          </node>
          <node ID="node_52" TEXT="Mac OS">
          </node>
          <node ID="node_53" TEXT="Linux/Unix">
          </node>
          <node ID="node_54" TEXT="Android/iOS">
          </node>
        </node>
        <node ID="node_22" TEXT="Utility Software">
          <node ID="node_55" TEXT="Disk Defragmenter">
          </node>
          <node ID="node_56" TEXT="Disk Cleaner">
          </node>
          <node ID="node_57" TEXT="Antivirus">
          </node>
          <node ID="node_58" TEXT="Backup Utility">
          </node>
        </node>
        <node ID="node_23" TEXT="Language Translators">
          <node ID="node_59" TEXT="Assembler">
          </node>
          <node ID="node_60" TEXT="Compiler">
          </node>
          <node ID="node_61" TEXT="Interpreter">
          </node>
        </node>
        <node ID="node_24" TEXT="Firmware &amp; Drivers">
        </node>
      </node>
      <node ID="node_7" TEXT="Application Software">
        <node ID="node_25" TEXT="General Purpose (MS Word, Photoshop)">
        </node>
        <node ID="node_26" TEXT="Special Purpose (GST Software)">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="Programming Languages">
      <node ID="node_8" TEXT="Low Level">
        <node ID="node_27" TEXT="Machine Language (Binary)">
        </node>
        <node ID="node_28" TEXT="Assembly Language (Mnemonics)">
        </node>
      </node>
      <node ID="node_9" TEXT="High Level">
        <node ID="node_29" TEXT="Procedural (FORTRAN, COBOL, BASIC, C)">
        </node>
        <node ID="node_30" TEXT="Object Oriented (Java, Python, C++, Ruby)">
        </node>
        <node ID="node_31" TEXT="Non-Procedural (SQL)">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="Internet Fundamentals">
      <node ID="node_10" TEXT="History &amp; Origins">
        <node ID="node_32" TEXT="ARPANET (1969)">
        </node>
        <node ID="node_33" TEXT="TCP/IP Protocol (Vint Cerf)">
        </node>
        <node ID="node_34" TEXT="WWW (Tim Berners-Lee)">
        </node>
        <node ID="node_35" TEXT="India: VSNL (1995)">
        </node>
      </node>
      <node ID="node_11" TEXT="Web Layers">
        <node ID="node_36" TEXT="Surface Web (4%)">
        </node>
        <node ID="node_37" TEXT="Deep Web (Private Data)">
        </node>
        <node ID="node_38" TEXT="Dark Web (TOR Browser)">
        </node>
      </node>
      <node ID="node_12" TEXT="Protocols">
        <node ID="node_39" TEXT="HTTP / HTTPS">
        </node>
        <node ID="node_40" TEXT="FTP (File Transfer)">
        </node>
        <node ID="node_41" TEXT="SMTP (Mail Send)">
        </node>
        <node ID="node_42" TEXT="POP3 / IMAP (Mail Receive)">
        </node>
      </node>
      <node ID="node_13" TEXT="Internet Address (URL)">
        <node ID="node_43" TEXT="Domain Name">
        </node>
        <node ID="node_44" TEXT="Top Level Domain (.com, .in, .org)">
        </node>
        <node ID="node_45" TEXT="IP Address (IPv4 vs IPv6)">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="Electronic Mail (Email)">
      <node ID="node_14" TEXT="Components">
        <node ID="node_46" TEXT="User Name">
        </node>
        <node ID="node_47" TEXT="CC &amp; BCC">
        </node>
      </node>
      <node ID="node_15" TEXT="Folders">
        <node ID="node_48" TEXT="Inbox / Outbox">
        </node>
        <node ID="node_49" TEXT="Spam / Junk">
        </node>
        <node ID="node_50" TEXT="Drafts / Trash">
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="Key Concepts &amp; Security">
      <node ID="node_16" TEXT="Net Neutrality">
      </node>
      <node ID="node_17" TEXT="Proxy Server">
      </node>
      <node ID="node_18" TEXT="Cloud Computing">
      </node>
      <node ID="node_19" TEXT="Phishing &amp; Spyware">
      </node>
      <node ID="node_20" TEXT="Starlink (Space Internet)">
      </node>
    </node>
  </node>
</map>